using UnityEngine;
using UnityEngine.SceneManagement;
using VContainer;
using VContainer.Unity;

public sealed class DungeonRuntimeLifetimeScope : LifetimeScope
{
    protected override void OnDestroy()
    {
        base.OnDestroy();
    }

    protected override void Configure(IContainerBuilder builder)
    {
        Scene scopeScene = gameObject.scene;
        DungeonSceneComponentQuery sceneQuery = new DungeonSceneComponentQuery(scopeScene);
        builder.RegisterInstance(sceneQuery)
            .AsSelf()
            .As<IDungeonSceneComponentQuery>();
        builder.RegisterEntryPoint<DungeonLegacyPersistenceMigration>(Lifetime.Singleton);
        builder.RegisterEntryPoint<SceneBuildableLeakValidator>(Lifetime.Singleton);
        builder.Register<UnityResourcesAssetLoader>(Lifetime.Singleton)
            .As<IResourcesAssetLoader>();
        builder.Register<ResourceDataScriptableObjectSource>(Lifetime.Singleton)
            .As<IDataScriptableObjectSource>();
        builder.Register<DataManager>(Lifetime.Singleton);
        builder.Register<DataManagerCatalog>(Lifetime.Singleton)
            .As<IDataCatalog>();
        builder.Register<BuildingDefinitionLookup>(Lifetime.Singleton)
            .As<IBuildingDefinitionLookup>();
        builder.Register<BuildingSummaryFormatter>(Lifetime.Singleton)
            .As<IBuildingSummaryFormatter>();
        builder.Register<GameManagerGameDataProvider>(Lifetime.Singleton)
            .As<IGameDataProvider>();
        builder.Register<GameManagerFloatingNumberFeedbackService>(Lifetime.Singleton)
            .As<IFloatingNumberFeedbackService>();
        builder.Register<UnityPlayerInputReader>(Lifetime.Singleton)
            .As<IPlayerInputReader>();
        builder.Register<EventSystemUiPointerBlocker>(Lifetime.Singleton)
            .As<IUiPointerBlocker>();
        builder.Register<PhysicsWorldPointerRaycaster>(Lifetime.Singleton)
            .As<IWorldPointerRaycaster>();
        builder.Register<ResourceTmpKoreanFontProvider>(Lifetime.Singleton)
            .As<ITmpKoreanFontProvider>();
        builder.Register<TmpKoreanFontService>(Lifetime.Singleton)
            .As<ITmpKoreanFontService>();
        builder.RegisterEntryPoint<DungeonUserSettingsService>(Lifetime.Singleton)
            .As<IDungeonUserSettingsService>();
        builder.RegisterEntryPoint<DungeonAudioController>(Lifetime.Singleton)
            .As<IDungeonAudioService>();
        builder.RegisterEntryPoint<DungeonSettingsUiController>(Lifetime.Singleton)
            .As<IDungeonSettingsUi>();
        builder.Register<ShopStockCatalog>(Lifetime.Singleton)
            .As<IShopStockCatalog>();
        builder.Register<GridSystemProvider>(Lifetime.Singleton)
            .As<IGridSystemProvider>();
        builder.Register<WorldDropZoneQuery>(Lifetime.Singleton)
            .As<IWorldDropZoneQuery>();
        builder.Register<ResourceDungeonItemCatalogProvider>(Lifetime.Singleton)
            .As<IDungeonItemCatalogProvider>();
        builder.Register<ResourceItemHaulingSettingsProvider>(Lifetime.Singleton)
            .As<IItemHaulingSettingsProvider>();
        builder.RegisterEntryPoint<WorldItemStackRuntime>(Lifetime.Singleton)
            .As<IWorldItemStackRuntime>();
        builder.RegisterEntryPoint<ItemStackViewToggleRuntime>(Lifetime.Singleton);
        builder.Register<DungeonBackdropSpriteTilingFactory>(Lifetime.Singleton)
            .As<IDungeonBackdropSpriteTilingFactory>();
        builder.Register<WorldInfoClickSelectionService>(Lifetime.Singleton)
            .As<IWorldInfoClickSelector>();
        builder.RegisterEntryPoint<WorldInfoClickInputController>(Lifetime.Singleton);
        builder.Register<DungeonGridBuildingControllerProvider>(Lifetime.Singleton)
            .As<IDungeonGridBuildingControllerProvider>();
        builder.Register<SceneMainCameraProvider>(Lifetime.Singleton)
            .As<IMainCameraProvider>();
        builder.Register<SceneCameraWorldPointerPositionProvider>(Lifetime.Singleton)
            .As<IWorldPointerPositionProvider>();
        builder.Register<GridTextureProvider>(Lifetime.Singleton)
            .As<IGridTextureProvider>();
        builder.Register<GridBuildingObjectFactory>(Lifetime.Singleton)
            .As<IGridBuildingObjectFactory>();
        builder.Register<ModularFacilityWorldSaveService>(Lifetime.Singleton)
            .As<IModularFacilityWorldSaveService>();
        builder.Register<CharacterWorldSaveService>(Lifetime.Singleton)
            .As<ICharacterWorldSaveService>()
            .As<ICharacterIdRegistry>();
        builder.Register<OperatingDaySettlementRuntimeProvider>(Lifetime.Singleton)
            .As<IOperatingDaySettlementRuntimeProvider>();
        builder.Register<OperatingDaySettlementSaveService>(Lifetime.Singleton)
            .As<IOperatingDaySettlementSaveService>();
        builder.Register<EventAlertRuntimeProvider>(Lifetime.Singleton)
            .As<IEventAlertRuntimeProvider>();
        builder.Register<EventAlertSaveService>(Lifetime.Singleton)
            .As<IEventAlertSaveService>();
        builder.Register<OffenseSaveService>(Lifetime.Singleton)
            .As<IOffenseSaveService>();
        builder.Register<InvasionSaveService>(Lifetime.Singleton)
            .As<IInvasionSaveService>();
        builder.Register<DungeonGameSaveService>(Lifetime.Singleton)
            .As<IDungeonGameSaveService>();
        builder.Register<DungeonSaveSlotCatalog>(Lifetime.Singleton)
            .As<IDungeonSaveSlotCatalog>();
        builder.Register<DungeonSceneNavigator>(Lifetime.Singleton)
            .As<IDungeonSceneNavigator>();
        builder.Register<DungeonGameSaveSlotService>(Lifetime.Singleton)
            .As<IDungeonGameSaveSlotService>();
        builder.RegisterEntryPoint<DungeonAutosaveService>(Lifetime.Singleton)
            .As<IDungeonSaveCommandService>();
        builder.RegisterEntryPoint<DungeonSaveUiController>(Lifetime.Singleton);
        builder.RegisterEntryPoint<DungeonGameplayLaunchController>(Lifetime.Singleton);
        builder.Register<GridGhostObjectResolver>(Lifetime.Singleton)
            .As<IGridGhostObjectResolver>();
        builder.Register<GridConstructButtonFactory>(Lifetime.Singleton)
            .As<IGridConstructButtonFactory>();
        builder.Register<FacilityEvolutionRuntimeProvider>(Lifetime.Singleton)
            .As<IFacilityEvolutionRuntimeProvider>();
        builder.Register<FacilitySynthesisRuntimeProvider>(Lifetime.Singleton)
            .As<IFacilitySynthesisRuntimeProvider>();
        builder.Register<DataCatalogFacilitySynthesisRecipeCatalog>(Lifetime.Singleton)
            .As<IFacilitySynthesisRecipeCatalog>();
        builder.Register<FacilitySynthesisRecipeQuery>(Lifetime.Singleton)
            .As<IFacilitySynthesisRecipeQuery>();
        builder.Register<DataCatalogFacilityEvolutionRecipeProvider>(Lifetime.Singleton)
            .As<IFacilityEvolutionRecipeProvider>();
        builder.Register<FacilityEvolutionRecipeQuery>(Lifetime.Singleton)
            .As<IFacilityEvolutionRecipeQuery>();
        builder.Register<SceneFacilityEvolutionWarehouseInventoryQuery>(Lifetime.Singleton)
            .As<IFacilityEvolutionWarehouseInventoryQuery>();
        builder.Register<WarehouseFacilityEvolutionResourceProvider>(Lifetime.Singleton)
            .As<IFacilityEvolutionResourceProvider>();
        builder.Register<DataCatalogFacilityEvolutionRecordTokenDefinitionProvider>(Lifetime.Singleton)
            .As<IFacilityEvolutionRecordTokenDefinitionProvider>();
        builder.Register<DefaultFacilityEvolutionRecordTokenConsumer>(Lifetime.Singleton)
            .As<IFacilityEvolutionRecordTokenConsumer>();
        builder.Register<GridFacilityEvolutionBuildingReplacerFactory>(Lifetime.Singleton)
            .As<IFacilityEvolutionBuildingReplacerFactory>();
        builder.Register<FacilityEvolutionRecordComponentFactory>(Lifetime.Singleton)
            .As<IFacilityEvolutionRecordComponentFactory>();
        builder.Register<FacilityEvolutionRecordComponentService>(Lifetime.Singleton)
            .As<IFacilityEvolutionRecordComponentService>()
            .As<IFacilityEvolutionRecordProvider>();
        builder.Register<FacilityEvolutionRecordEventRecorder>(Lifetime.Singleton)
            .As<IFacilityEvolutionRecordEventRecorder>();
        builder.Register<FacilityEvolutionStateComponentFactory>(Lifetime.Singleton)
            .As<IFacilityEvolutionStateComponentFactory>();
        builder.Register<DataCatalogCodexReferenceCatalog>(Lifetime.Singleton)
            .As<ICodexReferenceCatalog>();
        builder.Register<CodexReferenceImporter>(Lifetime.Singleton)
            .As<ICodexReferenceImporter>();
        builder.Register<CodexRuntimeProvider>(Lifetime.Singleton)
            .As<ICodexRuntimeProvider>();
        builder.Register<InvasionThreatRuntimeProvider>(Lifetime.Singleton)
            .As<IInvasionThreatRuntimeProvider>();
        builder.Register<InvasionDirectorRuntimeProvider>(Lifetime.Singleton)
            .As<IInvasionDirectorRuntimeProvider>();
        builder.RegisterEntryPoint<DungeonRunFlowRuntime>(Lifetime.Singleton)
            .As<IDungeonRunFlowRuntime>();
        builder.Register<ResourceFacilityCrimeSettingsProvider>(Lifetime.Singleton)
            .As<IFacilityCrimeSettingsProvider>();
        builder.Register<FacilityCrimeRiskEvaluator>(Lifetime.Singleton)
            .As<IFacilityCrimeRiskEvaluator>();
        builder.Register<InvasionThreatWorldSampler>(Lifetime.Singleton)
            .As<IInvasionThreatWorldSampler>();
        builder.Register<ResourceInvasionIntruderDataProvider>(Lifetime.Singleton)
            .As<IInvasionIntruderDataProvider>();
        builder.Register<InvasionIntruderContext>(Lifetime.Singleton)
            .As<IInvasionIntruderContext>();
        builder.Register<InvasionIntruderRuntimeFactory>(Lifetime.Singleton)
            .As<IInvasionIntruderFactory>();
        builder.Register<DefenseStatusRuntimeFactory>(Lifetime.Singleton)
            .As<IDefenseStatusRuntimeFactory>();
        builder.Register<DefenseStatusRuntimeService>(Lifetime.Singleton)
            .As<IDefenseStatusRuntimeService>();
        builder.Register<RunVariableRuntimeProvider>(Lifetime.Singleton)
            .As<IRunVariableRuntimeProvider>();
        builder.Register<RunVariableRuntimeReader>(Lifetime.Singleton)
            .As<IRunVariableRuntimeReader>();
        builder.Register<ResourceRunCharacterCatalog>(Lifetime.Singleton)
            .As<IRunCharacterCatalog>();
        builder.Register<ResourceOwnerCandidateCatalog>(Lifetime.Singleton)
            .As<IOwnerCandidateCatalog>();
        builder.Register<RunStartVariableCatalog>(Lifetime.Singleton)
            .As<IRunStartVariableCatalog>();
        builder.Register<RunStartVariableSelector>(Lifetime.Singleton)
            .As<IRunStartVariableSelector>();
        builder.Register<CharacterVisualRootFactory>(Lifetime.Singleton)
            .As<ICharacterVisualRootFactory>();
        builder.Register<OwnerRunDataProvider>(Lifetime.Singleton)
            .As<IOwnerRunDataProvider>()
            .As<IOwnerRunManagerProvider>();
        builder.Register<OwnerCharacterFactory>(Lifetime.Singleton)
            .As<IOwnerCharacterFactory>();
        builder.Register<OwnerSelectionOptionButtonFactory>(Lifetime.Singleton)
            .As<IOwnerSelectionOptionButtonFactory>();
        builder.Register<OwnerRunLifecycleService>(Lifetime.Singleton)
            .As<IOwnerRunLifecycleService>();
        builder.Register<CharacterSpawnerProvider>(Lifetime.Singleton)
            .As<ICharacterSpawnerProvider>();
        builder.Register<CharacterSpawnObjectFactory>(Lifetime.Singleton)
            .As<ICharacterSpawnObjectFactory>();
        builder.Register<StaffDiscontentRuntimeProvider>(Lifetime.Singleton)
            .As<IStaffDiscontentRuntimeProvider>();
        builder.Register<StaffDiscontentRuntimeService>(Lifetime.Singleton)
            .As<IStaffDiscontentRuntimeService>();
        builder.Register<DungeonWorkforceReplanService>(Lifetime.Singleton)
            .As<IWorkforceReplanService>();
        builder.Register<LocalLlmRuntimeProvider>(Lifetime.Singleton)
            .As<ILocalLlmRuntimeProvider>();
        builder.Register<ResourceCharacterSkillSystemSettingsProvider>(Lifetime.Singleton)
            .As<ICharacterSkillSystemSettingsProvider>();
        builder.Register<CharacterPopulationService>(Lifetime.Singleton)
            .As<ICharacterPopulationService>();
        builder.Register<StartPartyPreparationService>(Lifetime.Singleton)
            .As<IStartPartyPreparationService>();
        builder.RegisterEntryPoint<CharacterSkillGenerationService>(Lifetime.Singleton)
            .As<ICharacterSkillGenerationService>();
        builder.RegisterEntryPoint<CharacterSkillAutomaticTriggerRuntime>(Lifetime.Singleton);
        builder.Register<CharacterLogNarrativeService>(Lifetime.Singleton)
            .AsSelf()
            .As<ICharacterLogNarrativeService>();
        builder.Register<AiDirectorContextSceneQuery>(Lifetime.Singleton)
            .As<IAiDirectorContextSceneQuery>();
        builder.Register<CharacterAiFacilityLookup>(Lifetime.Singleton)
            .As<ICharacterAiFacilityLookup>();
        builder.Register<FacilityCandidateCacheStore>(Lifetime.Singleton)
            .As<IFacilityCandidateCache>();
        builder.Register<RoomLayoutCache>(Lifetime.Singleton)
            .As<IRoomLayoutCache>();
        builder.Register<ResourceRoomEnvironmentSettingsProvider>(Lifetime.Singleton)
            .As<IRoomEnvironmentSettingsProvider>();
        builder.Register<RoomEnvironmentEvaluator>(Lifetime.Singleton)
            .As<IRoomEnvironmentEvaluator>();
        builder.Register<RoomEnvironmentQuery>(Lifetime.Singleton)
            .As<IRoomEnvironmentQuery>();
        builder.RegisterEntryPoint<RoomEnvironmentExperienceService>(Lifetime.Singleton);
        builder.RegisterEntryPoint<RoomInspectionRuntime>(Lifetime.Singleton);
        builder.Register<RoomFacilityPolicyService>(Lifetime.Singleton)
            .As<IRoomFacilityPolicy>();
        builder.Register<CharacterBehaviorTreeRuntimeConfigurator>(Lifetime.Singleton)
            .As<ICharacterBehaviorTreeRuntimeConfigurator>();
        builder.Register<CharacterAiSchedulingService>(Lifetime.Singleton)
            .As<ICharacterAiSchedulingService>();
        builder.Register<CharacterSocialMemoryFactory>(Lifetime.Singleton)
            .As<ICharacterSocialMemoryFactory>();
        builder.Register<CharacterFeedbackBubbleFactory>(Lifetime.Singleton)
            .As<ICharacterFeedbackBubbleFactory>();
        builder.Register<CharacterFeedbackBubbleViewFactory>(Lifetime.Singleton)
            .As<ICharacterFeedbackBubbleViewFactory>();
        builder.Register<CharacterDialogueBubbleFactory>(Lifetime.Singleton)
            .As<ICharacterDialogueBubbleFactory>();
        builder.Register<CharacterAiJobGiverCatalog>(Lifetime.Singleton)
            .As<ICharacterAiJobGiverCatalog>();
        builder.Register<CharacterAiDecisionPipeline>(Lifetime.Singleton)
            .As<ICharacterAiDecisionPipeline>();
        builder.Register<ResourceCharacterAiActionAssetCatalog>(Lifetime.Singleton)
            .As<ICharacterAiActionAssetCatalog>();
        builder.Register<SocialReputationRuntimeProvider>(Lifetime.Singleton)
            .As<ISocialReputationRuntimeProvider>();
        builder.Register<SocialReputationBiasService>(Lifetime.Singleton)
            .As<ISocialReputationBiasService>();
        builder.Register<RegularCustomerRuntimeProvider>(Lifetime.Singleton)
            .As<IRegularCustomerRuntimeProvider>();
        RegularCustomerRuntime sceneRegularCustomerRuntime =
            sceneQuery.First<RegularCustomerRuntime>(includeInactive: true);
        if (sceneRegularCustomerRuntime != null)
        {
            builder.RegisterComponent(sceneRegularCustomerRuntime);
        }
        else
        {
            builder.RegisterComponentOnNewGameObject<RegularCustomerRuntime>(
                    Lifetime.Singleton,
                    nameof(RegularCustomerRuntime))
                .UnderTransform(transform);
        }

        builder.Register<RecruitedCharacterActivationService>(Lifetime.Singleton)
            .As<IRecruitedCharacterActivationService>();
        builder.Register<DailyFacilityShopRuntimeProvider>(Lifetime.Singleton)
            .As<IDailyFacilityShopRuntimeProvider>();
        builder.Register<DataCatalogFacilityShopCatalog>(Lifetime.Singleton)
            .As<IFacilityShopCatalog>();
        builder.Register<FacilityShopUnlockStateService>(Lifetime.Singleton)
            .As<IFacilityShopUnlockStateService>();
        builder.Register<BlueprintResearchRuntimeProvider>(Lifetime.Singleton)
            .As<IBlueprintResearchRuntimeProvider>();
        builder.Register<BlueprintResearchWorkService>(Lifetime.Singleton)
            .As<IBlueprintResearchWorkService>();
        builder.Register<BlueprintResearchStateService>(Lifetime.Singleton)
            .As<IBlueprintResearchStateService>();
        builder.Register<MetaProgressionRuntimeProvider>(Lifetime.Singleton)
            .As<IMetaProgressionRuntimeProvider>();
        builder.Register<MetaProgressionRuntimeReader>(Lifetime.Singleton)
            .As<IMetaProgressionRuntimeReader>();
        builder.Register<MetaProfileStore>(Lifetime.Singleton)
            .As<IMetaProfileStore>();
        builder.RegisterEntryPoint<MetaProfilePersistenceService>(Lifetime.Singleton);
        builder.Register<DungeonRunTransitionService>(Lifetime.Singleton)
            .As<IDungeonRunTransitionService>();
        builder.Register<OffenseWorldMapRuntimeProvider>(Lifetime.Singleton)
            .As<IOffenseWorldMapRuntimeProvider>();
        builder.Register<OffenseRewardRuntimeProvider>(Lifetime.Singleton)
            .As<IOffenseRewardRuntimeProvider>();
        builder.Register<OffenseExpeditionRuntimeProvider>(Lifetime.Singleton)
            .As<IOffenseExpeditionRuntimeProvider>();
        builder.Register<OffenseExpeditionMemberQuery>(Lifetime.Singleton)
            .As<IOffenseExpeditionMemberQuery>();
        builder.Register<DungeonOffensePreparationService>(Lifetime.Singleton)
            .As<IOffensePreparationService>();
        builder.Register<ResourceExpeditionEquipmentCatalogProvider>(Lifetime.Singleton)
            .As<IExpeditionEquipmentCatalogProvider>();
        builder.Register<ExpeditionEquipmentRuntime>(Lifetime.Singleton)
            .As<IExpeditionEquipmentRuntime>();
        builder.RegisterEntryPoint<OffenseBattleRuntime>(Lifetime.Singleton)
            .As<IOffenseBattleRuntime>();
        builder.Register<DataCatalogOffenseRewardCatalog>(Lifetime.Singleton)
            .As<IOffenseRewardCatalog>();
        builder.Register<OffenseRewardSelector>(Lifetime.Singleton)
            .As<IOffenseRewardSelector>();
        builder.Register<OffenseMoneyRewardGrantHandler>(Lifetime.Singleton)
            .As<IOffenseRewardGrantHandler>();
        builder.Register<OffenseStockRewardGrantHandler>(Lifetime.Singleton)
            .As<IOffenseRewardGrantHandler>();
        builder.Register<OffenseRareFacilityRewardGrantHandler>(Lifetime.Singleton)
            .As<IOffenseRewardGrantHandler>();
        builder.Register<OffenseBlueprintRewardGrantHandler>(Lifetime.Singleton)
            .As<IOffenseRewardGrantHandler>();
        builder.Register<OffenseHumanFactionRewardGrantHandler>(Lifetime.Singleton)
            .As<IOffenseRewardGrantHandler>();
        builder.Register<OffenseRivalFactionRewardGrantHandler>(Lifetime.Singleton)
            .As<IOffenseRewardGrantHandler>();
        builder.Register<OffenseRecruitCandidateRewardGrantHandler>(Lifetime.Singleton)
            .As<IOffenseRewardGrantHandler>();
        builder.Register<OffensePrisonerRewardGrantHandler>(Lifetime.Singleton)
            .As<IOffenseRewardGrantHandler>();
        builder.Register<OffenseSpecialMonsterRewardGrantHandler>(Lifetime.Singleton)
            .As<IOffenseRewardGrantHandler>();
        builder.Register<OffenseRewardGrantService>(Lifetime.Singleton)
            .As<IOffenseRewardGrantService>();
        builder.Register<OffensePanelFactory>(Lifetime.Singleton)
            .As<IOffensePanelFactory>();
        builder.Register<OffenseBattlePanelFactory>(Lifetime.Singleton)
            .As<IOffenseBattlePanelFactory>();
        builder.RegisterEntryPoint<OffenseBattleUiController>(Lifetime.Singleton);
        builder.Register<OffensePanelButtonFactory>(Lifetime.Singleton)
            .As<IOffensePanelButtonFactory>();
        builder.Register<OffensePanelService>(Lifetime.Singleton)
            .As<IOffensePanelService>();
        builder.Register<OffenseRewardContextBuilder>(Lifetime.Singleton)
            .As<IOffenseRewardContextBuilder>();
        builder.Register<MetaRunResultBuilder>(Lifetime.Singleton)
            .As<IMetaRunResultBuilder>();
        builder.Register<RunResultPanelFactory>(Lifetime.Singleton)
            .As<IRunResultPanelFactory>();
        builder.Register<RunResultPanelService>(Lifetime.Singleton)
            .As<IRunResultPanelService>();
        builder.Register<CodexPanelFactory>(Lifetime.Singleton)
            .As<ICodexPanelFactory>();
        builder.Register<FacilitySynthesisPanelFactory>(Lifetime.Singleton)
            .As<IFacilitySynthesisPanelFactory>();
        builder.Register<FacilityEvolutionPanelFactory>(Lifetime.Singleton)
            .As<IFacilityEvolutionPanelFactory>();
        builder.Register<StaffWorkPriorityPanelUiFactory>(Lifetime.Singleton)
            .As<IStaffWorkPriorityPanelUiFactory>();
        builder.Register<StaffWorkPriorityPanelModelBuilder>(Lifetime.Singleton)
            .As<IStaffWorkPriorityPanelModelBuilder>();
        builder.Register<StaffWorkPriorityPanelFactory>(Lifetime.Singleton)
            .As<IStaffWorkPriorityPanelFactory>();
        builder.Register<P0FeatureSurfacePanelFactory>(Lifetime.Singleton)
            .As<IP0FeatureSurfacePanelFactory>();
        builder.Register<BuildingFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<ShopFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<WarehouseFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<OperationsFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<DefenseFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<ExpeditionFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<ResearchFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<CodexFeatureSurfacePresenter>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenter>();
        builder.Register<FeatureSurfaceTabPresenterRegistry>(Lifetime.Singleton)
            .As<IFeatureSurfaceTabPresenterRegistry>();
        builder.Register<UITabGeneratedPanelFactory>(Lifetime.Singleton)
            .As<IUITabGeneratedPanelFactory>();
        builder.Register<UITabTopButtonFactory>(Lifetime.Singleton)
            .As<IUITabTopButtonFactory>();
        builder.Register<EventAlertButtonFactory>(Lifetime.Singleton)
            .As<IEventAlertButtonFactory>();
        builder.Register<EventAlertViewUiFactory>(Lifetime.Singleton)
            .As<IEventAlertViewUiFactory>();
        builder.Register<EventAlertViewPresenterFactory>(Lifetime.Singleton)
            .As<IEventAlertViewPresenterFactory>();
        builder.Register<EventAlertCanvasProvider>(Lifetime.Singleton)
            .As<IEventAlertCanvasProvider>()
            .As<IDungeonUiCanvasProvider>();
        builder.RegisterEntryPoint<FirstRunObjectiveRuntime>(Lifetime.Singleton)
            .As<IFirstRunObjectiveRuntime>();
        builder.RegisterEntryPoint<DungeonPlayerAutomationBridge>(Lifetime.Singleton);
        builder.Register<NoticeFeedItemFactory>(Lifetime.Singleton)
            .As<INoticeFeedItemFactory>();
        builder.Register<NoticeFeedPresenter>(Lifetime.Singleton)
            .As<INoticeFeedPresenter>();
        builder.Register<CharacterSummaryRuntimeLogFactory>(Lifetime.Singleton)
            .As<ICharacterSummaryRuntimeLogFactory>();
        builder.RegisterInstance(CaptureSceneRuntimeReferences(sceneQuery));
        builder.Register<StaffWorkforceRuntimeQueryService>(Lifetime.Singleton)
            .As<IStaffWorkforceQueryService>();
        builder.Register<WorkGridResolver>(Lifetime.Singleton)
            .As<IWorkGridResolver>();
        builder.Register<BuildingManagementSummaryService>(Lifetime.Singleton)
            .As<IBuildingManagementSummaryService>();
        builder.Register<InvasionDefenseSummaryService>(Lifetime.Singleton)
            .As<IInvasionDefenseSummaryService>();
        builder.Register<OffenseTabSummaryService>(Lifetime.Singleton)
            .As<IOffenseTabSummaryService>();
        builder.Register<OperationTabSummaryService>(Lifetime.Singleton)
            .As<IOperationTabSummaryService>();
        builder.Register<ResearchCraftingSummaryService>(Lifetime.Singleton)
            .As<IResearchCraftingSummaryService>();
        builder.Register<CodexRecordSummaryService>(Lifetime.Singleton)
            .As<ICodexRecordSummaryService>();
        builder.Register<BuildingTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<StaffTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<ShopTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<WarehouseTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<OperationsTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<DefenseTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<ExpeditionTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<ResearchTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<CodexTabContentPresenter>(Lifetime.Singleton)
            .As<IUITabContentPresenter>();
        builder.Register<UITabContentTextProvider>(Lifetime.Singleton)
            .As<IUITabContentTextProvider>();
        builder.Register<UiPopupService>(Lifetime.Singleton)
            .As<IUiPopupService>();
        builder.RegisterComponentOnNewGameObject<ItemPileInfoPanel>(
                Lifetime.Singleton,
                nameof(ItemPileInfoPanel))
            .UnderTransform(transform);
        builder.Register<GameManagerFloatingIconFeedbackService>(Lifetime.Singleton)
            .As<IFloatingIconFeedbackService>();

        builder.RegisterBuildCallback((resolver) =>
        {
            InjectSceneHierarchy(resolver, scopeScene);
            resolver.Resolve<ItemPileInfoPanel>();
            resolver.Resolve<RegularCustomerRuntime>();
        });
    }

    private static void InjectSceneHierarchy(IObjectResolver resolver, Scene scopeScene)
    {
        if (!scopeScene.IsValid())
        {
            throw new System.InvalidOperationException(
                "Cannot inject DungeonStory scene components because the owning scene is invalid.");
        }

        GameObject[] roots = scopeScene.GetRootGameObjects();
        for (int i = 0; i < roots.Length; i++)
        {
            resolver.InjectGameObject(roots[i]);
        }
    }

    private static DungeonSceneRuntimeReferences CaptureSceneRuntimeReferences(IDungeonSceneComponentQuery sceneQuery)
    {
        return new DungeonSceneRuntimeReferences(
            sceneQuery.First<UIManager>(includeInactive: true),
            sceneQuery.First<OperatingDaySettlementRuntime>(includeInactive: true),
            sceneQuery.First<EventAlertRuntime>(includeInactive: true),
            sceneQuery.First<RunVariableRuntime>(includeInactive: true),
            sceneQuery.First<Canvas>(includeInactive: true));
    }
}
